version: '3'
services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
